openapi: 3.0.0
info:
  title: Book Management API
  version: 1.0.0
  description: API for managing a collection of books.
servers:
  - url: http://localhost:5000/api
paths:
  /books:
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedDate:
                  type: string
                  format: date
                numberOfPages:
                  type: integer
      responses:
        '201':
          description: Successfully created book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    get:
      summary: Retrieve a list of all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  
  /books/{id}:
    get:
      summary: Get details of a specific book
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the book to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

    put:
      summary: Update a book's details
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the book to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                numberOfPages:
                  type: integer
      responses:
        '200':
          description: Successfully updated book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

    delete:
      summary: Delete a book
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the book to delete.
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted book

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        publishedDate:
          type: string
          format: date
        numberOfPages:
          type: integer